### ISSUE TITLE
Ch04/challenge - swap values in `TrimPrefix`

### ISSUE THREAD

**Issue by georgettica** [LinkedInLearning/secure-coding-go-3009233#1]
this makes using the provided functions less reliable

https://github.com/LinkedInLearning/secure-coding-go-3009233/blob/3907e93d2e553f09deb653b8869e0924deb1b790/Ch04/challenge/auth.go#L27

**Comment by georgettica** [comment]
an additional issue is using the `&` and not the `|` to set the values
https://github.com/LinkedInLearning/secure-coding-go-3009233/blob/3907e93d2e553f09deb653b8869e0924deb1b790/Ch04/challenge/auth.go#L35

**Comment by tebeka** [comment]
Thanks. Sorry for the late reply - pretty swampped. Will try to have a look next week.

**Comment by tebeka** [comment]
Fixed in #2

**Comment by georgettica** [comment]
ty!
